CREATE TABLE UNIDAD_MEDIDA(
	UnidM_Nombre VARCHAR(45) PRIMARY KEY
	)

INSERT INTO UNIDAD_MEDIDA VALUES ('Metro'), ('Unidad');

CREATE TABLE MATERIAL(
	Mat_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Mat_Nombre VARCHAR(50) NOT NULL,
	Mat_Precio FLOAT NOT NULL,
	Mat_UnitMedida VARCHAR (45) NOT NULL,
	FOREIGN KEY (Mat_UnitMedida) REFERENCES UNIDAD_MEDIDA (UnidM_Nombre)
	)

	CREATE TABLE CATEGORIA(
	Categ_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Categ_Nombre VARCHAR(25) NOT NULL
	)

CREATE TABLE SUBCATEGORIA(
	SubCa_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	SubCa_Nombre VARCHAR(50) NOT NULL,
	SubCa_Categoria INT NOT NULL,
	FOREIGN KEY (SubCa_Categoria) REFERENCES CATEGORIA (Categ_ID)
	)


CREATE TABLE TIPOTRABAJO(
	TipoT_Nombre VARCHAR(12) NOT NULL PRIMARY KEY
	)

CREATE TABLE PRODUCTO(
	Prod_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Prod_Trabajo VARCHAR(12) NOT NULL,
	Prod_Cantidad INT NOT NULL,
	Prod_Descripcion VARCHAR(250) NULL,
	Prod_CostoProduccion FLOAT NOT NULL,
	Prod_SubCategoria INT NOT NULL,
	FOREIGN KEY (Prod_SubCategoria) REFERENCES SUBCATEGORIA (SubCa_ID),
	FOREIGN KEY (Prod_Trabajo) REFERENCES TIPOTRABAJO (TipoT_Nombre)
	)

CREATE TABLE CARPA_MATERIAL(
	CarpM_Producto INT NOT NULL,
	CarpM_Material INT NOT NULL,
	CarpM_Cantidad INT NOT NULL,
	FOREIGN KEY (CarpM_Material) REFERENCES MATERIAL (Mat_ID),
	FOREIGN KEY (CarpM_Producto) REFERENCES PRODUCTO (Prod_ID)
	)

CREATE TABLE PROVEEDOR(
	Provee_ID INT NOT NULL PRIMARY KEY,
	Provee_Nombre VARCHAR(60) NOT NULL,
	Provee_Telefono VARCHAR(11) NULL,
	Provee_Descripcion VARCHAR(200) NOT NULL
	)

CREATE TABLE PROVEEDOR_MATERIAL(
	ProveM_Proveedor INT NOT NULL,
	ProveM_Material INT NOT NULL,
	ProveM_Cantidad INT NOT NULL,
	ProveM_Fecha DATE NOT NULL,
	FOREIGN KEY (ProveM_Proveedor)	 REFERENCES PROVEEDOR (Provee_ID),
	FOREIGN KEY (ProveM_Material) REFERENCES MATERIAL (Mat_ID)
	)

CREATE TABLE ROL(
	Rol_Nombre VARCHAR(15) NOT NULL PRIMARY KEY
	)

CREATE TABLE CARGO(
	Cargo_Nombre VARCHAR(25) NOT NULL PRIMARY KEY
	)

CREATE TABLE ESTADO(
	Estado_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Estado_Nombre VARCHAR (15) NOT NULL
	)

CREATE TABLE PERSONA(
	Perso_ID VARCHAR(15) NOT NULL PRIMARY KEY,
	Perso_Nombre VARCHAR(25) NOT NULL,
	Perso_Apellido VARCHAR NOT NULL,
	Perso_Telefono VARCHAR(15) NOT NULL
	)

CREATE TABLE EMPLEADO(
	Emple_ID VARCHAR(15) NOT NULL PRIMARY KEY,
	Emple_Cargo VARCHAR(25) NOT NULL,
	Emple_Estado INT NOT NULL,
	Emple_Rol VARCHAR(15) NOT NULL,
	FOREIGN KEY (Emple_Rol) REFERENCES ROL (Rol_Nombre),
	FOREIGN KEY (Emple_ID) REFERENCES PERSONA (Perso_ID),
	FOREIGN KEY (Emple_Estado) REFERENCES ESTADO (Estado_ID),
	FOREIGN KEY (Emple_Cargo) REFERENCES CARGO (Cargo_Nombre)
	)

CREATE TABLE LOGIN(
	Login_Usuario VARCHAR(15) NOT NULL PRIMARY KEY,
	Login_Pass VARCHAR(25) NOT NULL,
	FOREIGN KEY (Login_Usuario) REFERENCES EMPLEADO (Emple_ID)
	)

CREATE TABLE CLIENTE(
	Clien_ID VARCHAR(15) NOT NULL PRIMARY KEY,
	FOREIGN KEY (Clien_ID) REFERENCES PERSONA (Perso_ID)
	)


CREATE TABLE TRABAJO(
	Trab_Producto INT NOT NULL,
	Trab_Empleado VARCHAR(15) NOT NULL,
	Trab_Pago FLOAT NULL,
	FOREIGN KEY (Trab_Producto) REFERENCES PRODUCTO (Prod_ID),
	FOREIGN KEY (Trab_Empleado) REFERENCES PERSONA (Perso_ID)
	)

CREATE TABLE VENTA(
	Venta_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Venta_Producto INT NOT NULL,
	Venta_Dias INT NOT NULL,
	Venta_FechaPedido DATE NOT NULL,
	Venta_FechaEntrega DATE NOT NULL,
	Venta_Cliente VARCHAR(15) NOT NULL,
	Venta_CostoVenta FLOAT NOT NULL,
	FOREIGN KEY (Venta_Cliente) REFERENCES CLIENTE (Clien_ID),
	FOREIGN KEY (Venta_Producto) REFERENCES PRODUCTO (Prod_ID)
	)